spring.application.name=tp1c2026
server.port=8081 
# Agrego un port para futuro heath check
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=${TELEGRAM_BOT_USERNAME}
backend.url=http://localhost:8080
chatlinks.file=./chat-links.json